### ISSUE TITLE
GPS Location Reported to Signal K Incorrect

### ISSUE THREAD

**Issue by zirinisp** [meri-imperiumi/signalk-teltonika-rutx11#90] opened 2022-05-26 07:27 UTC
I am getting the following positions reported under the data browser on my signal k server.

The first 2 are from my plotter and the gps antenna attached to my raspberry. The last one is the one reported from teltonika and the values are incorrect or have a different format than the one expected.

navigation.position | {   "longitude": 24.78245,   "latitude": 37.8575033 } |   | 05/26 10:24:56 | 1.1  (129039)

navigation.position | {   "longitude": 24.78244,   "latitude": 37.85752333333333 } |   | 05/26 10:24:57 | gps_pi.GP  (RMC)

navigation.position | {   "latitude": 7.693130305972483e-25,   "longitude": -3.7512190583080584e-32 } |   | 05/26 10:24:32 | signalk-teltonika-rutx11.XX

When I go to the teltonika interface and check my position I get the following:

FIX TIME | LATITUDE | LONGITUDE
-- | -- | --
5/26/2022, 7:28:05 AM | 37.857509 | 24.782490

Which is in line with the one reported from the first 2 devices.

**Comment by nmbath** [comment] 2022-06-30 15:01
The issue lies in line 99 and 100. The data is being read as little endian and is actually in big endian.

**Comment by bergie** [comment] 2023-04-27 09:13
This is weird, I'm unable to reproduce:

<img width="919" alt="Screenshot 2023-04-27 at 11 12 39" src="https://user-images.githubusercontent.com/3346/234816650-8347a9eb-c868-4691-908b-47e67ddb0ff3.png">

**Comment by sillymander** [comment] 2023-04-29 01:23
Confirmed that code should be bigendian for the RUT 955

**Comment by nmbath** [comment] 2023-07-22 18:21
For RUTX11 looks like it is also bigendian. My system is reporting me as just north of the equator, when I am in the UK.

**Comment by msirolla** [comment] 2023-07-27 09:55
I have the exact same issue, using latest software. Server running on Cerbo GX, wired via LAN into a Teltonika RUTX11 with latest firmware.
Would it be possible to have a fix?

**Comment by dsuckow** [comment] 2024-01-06 08:44
Have a RUTX11 and it seems also provided as big endian, added a config parameter to switch between big endian and little endian.

**Comment by msirolla** [comment] 2024-01-06 12:43
> Have a RUTX11 and it seems also provided as big endian, added a config parameter to switch between big endian and little endian.

Many thanks! Would you be so kind to please provide basic instructions on how I can get your update into my Signal K system? I’m still new at this 🙂

**Comment by bergie** [comment] 2024-01-07 11:49
Should be fixed in 0.6.0 thanks to #125

**Closed by bergie** 2024-01-07 11:49 UTC
